### ISSUE TITLE
godo createdb leaves terminal in no echo state

### ISSUE THREAD

**Issue by jackc** [mgutz/dat#1]
After running godo createdb in OSX with iterm the terminal no longer echos characters. Can work-around by running `reset`, but still confusing/annoying.

**Comment by mgutz** [comment]
Hmm i use an external package for that. When you say iterm, do you mean iterm2? I'll try to reproduce.

**Comment by mgutz** [comment]
I'm using different package for password prompt. I hope it works for you. You'll need to update

```sh
go get -u gopkg.in/godo.v1/cmd/godo
```
