### ISSUE TITLE
undefined: runner.LogQueriesThreshold

### ISSUE THREAD

**Issue by saggit** [mgutz/dat#16]
hi, man
There are two problem in README Getting Started part

* `UpdatedAt dat.Nulltime  `db:"updated_at"` should be `UpdatedAt dat.NullTime  `db:"updated_at"` the t should be Uppercase.

* when i try to run demo code in Getting Start, i get the error: undefined: runner.LogQueriesThreshold

env: mac 10.10 golang1.4.2

**Comment by mgutz** [comment]
You must be looking at master. I have not tagged it yet for release. It will be in v1.1.0 release probably this weekend. W'ere still testing caching.
