### ISSUE TITLE
Why the custom interpolation logic for `dat.NullTime`?

### ISSUE THREAD

**Issue by JustinTulloss** [mgutz/dat#22]
I was trying to figure out why `dat.NullTime` instances were being inserted as the 0 value instead of NULL when `EnableInterpolation` is true. It turns out it's because interpolating prefers the `Interpolator` interface to the `Valuer` interface, and `dat.NullTime` implements this here: https://github.com/mgutz/dat/blob/v1/types.go#L264.

Besides the fact that it should definitely return NULL if the time is not valid, I'm not sure why it implements the interpolator interface in the first place. Is the default serialization of `time.Time` not sufficient? If you remove that function, NULLs work correctly and times get serialized, but I'm unclear if they're being serialized in the same manner or not.

**Comment by mgutz** [comment]
That looks like a bug. You're right it should return NULL if it is invalid. The default serialized doesn't include nanoseconds which I needed for a recent project.

**Comment by JustinTulloss** [comment]
Awesome, thanks! A couple more things.

- The provided patch doesn't work. It returns `"NULL"`, which then gets quoted as the string `'NULL'` in the sql statement, rather than just the literal `NULL`. This is true at least for the `UpsertBuilder`.
- I don't think it's great to have `dat.NullTime` have different serializations depending on whether `dat.EnableInterpolation` is true or false. Perhaps there should be a second type, `dat.NanoNullTime`?

**Comment by mgutz** [comment]
Sorry about that. Fixed

You should be able to use pq.NullTime if you want the default behavior. Interpolate will use a Valuer interface.

**Comment by JustinTulloss** [comment]
Thanks for fixing the NULL thing.

I'm going to continue to take issue with your `pq.NullTime` response even though that's a perfectly reasonable explanation and it's your project and you can do whatever you want :)

- You say in the docs to use `dat.NullTime`, without talking about its different behavior depending on the value of `dat.EnableInterpolation`
- There are further improvements beyond interpolation that you've implemented in `dat.NullTime` around JSONification.

A reasonable way of fixing this in my mind would be to override the Valuer function as well, so at least it's consistent. I'll actually put up a PR for that and we can continue the discussion there if you're so inclined.

**Comment by mgutz** [comment]
Please do, thx
