### ISSUE TITLE
OrderBy needs to accept arguments like Where does

### ISSUE THREAD

**Issue by flyingmutant** [mgutz/dat#29]
To enable things like 

```sql
ORDER BY table.col <-> $1
```

**Comment by nickmarx12345678** [comment]
+1,
Also have run into cases where this functionality in `FROM` would be handy too

**Comment by mgutz** [comment]
I'm not familiar with such expression. Is the `$1` a column name or value? Can you provide some examples?

**Comment by flyingmutant** [comment]
`<->` in the example above is from [pg_trgm](http://www.postgresql.org/docs/9.5/static/pgtrgm.html); `$1` is a value. This is an example of ordering the result set based on trigram distance to some user input (query).
