### ISSUE TITLE
Support for scoped queries

### ISSUE THREAD

**Issue by pkieltyka** [mgutz/dat#4]
The query syntax is pretty nice, but it would be nice to not have to every expression as a string. Specifically, for the `Where()`.

What do you think of this form:

```go
err = sess.Select("*").From("posts").Where(dat.Cond{"id >", 100}).QueryStructs(&posts))
```

dat.Cond is defined as:
```go
type Cond map[string]interface{}
```
and the cool thing is you can easily have cond := dat.Cond{} and then do cond["field"] = "val"

and then build the condition string as you build the entire query.

if `.Where()` accepted an `...interface{}` then both forms could easily be supported. Or leave .Where() and add .Scope() or .WhereCond(), ...

also, is Select("*") implied?

**Comment by mgutz** [comment]
Select() columns are explicit, I'll add an error when argument is missing.

What about something like this which supports joins as well?

```go
type Args map[string]interface{}
type Scope struct {
	SQL  string
	Args Args
}

// :TABLE is  the table name from builder
scope := NewScope(`
	INNER JOIN accounts A on (:TABLE.id = A.id)
	WHERE
		:TABLE.user = :name
		and A.amount > :amount`,
        // default args can be overriden
	dat.Args{
		"name":   "Jane",
		"amount": 100,
	},
)

runner.Select("*").From("users").Scope(scope, dat.Args{"name": "mgutz"}).QueryStructs(&users)
```

`SelectBuilder.Scope` clones scope's arguments then merges in dat.Args{} before building the SQL.

**Comment by mgutz** [comment]
BTW, you can use multiple `Where` clauses and there is also dat.Eq{} https://github.com/mgutz/dat/blob/master/select_test.go#L168

**Comment by pkieltyka** [comment]
nice. I think that scope syntax would work.

**Comment by mgutz** [comment]
FYI, I changed this slightly. Scope uses plain SQL.

```
runner.Select("users.*").From("users").ScopeMap(scope, dat.M{"name": "jane"}).QueryStructs(&users)
```
