### ISSUE TITLE
Use dependency management solution

### ISSUE THREAD

**Issue by kenkouot** [mgutz/dat#43]
With `vendor/` on by default in Go 1.6, it would be really convenient if dat used it for it's dependencies. We use [glide](https://github.com/Masterminds/glide) for our dependency management, which will trace our dependencies (including dat) if they implement a vendor folder, or use Glide, godep, GB or GPM.

**Comment by mgutz** [comment]
Good idea. I'll add Dockerfile with Glide to build and test.

**Comment by kenkouot** [comment]
Looks like this was added to master :D Much thanks!

**Comment by mgutz** [comment]
The glide deps in master has issues. I will be updating in the next days with Timeout feature which also fixes dependencies.
