### ISSUE TITLE
Add "ForUpdate" to SelectBuilder?

### ISSUE THREAD

**Issue by sbowman** [mgutz/dat#45]
It would be nice to have a ForUpdate function in the SelectBuilder for working with transactions and row-level locking.  

Or is there another approach I'm missing?

**Comment by mgutz** [comment]
We predominately use SQL statements so it's never come up. It's easy to add. I prefer a single `For` method

```go
// For("update")
// For("share")
For(options ...string)
```

rather than

```go
ForShare(options ...string)
ForUpdate(options ...string)
```

Thoughts?

**Comment by sbowman** [comment]
I agree. A For() method would be way more flexible than individual methods.

**Comment by alkchr** [comment]
What as for type safety? From that perspective `ForShare` / `ForUpdate` is a better option.

**Comment by mgutz** [comment]
@alkchr Unfortunately, there are 4 variations of `For` with options in PG 9.5. Who knows if the PG team will add more in the future. I'd rather not pollute the API surface with every variant.
