### ISSUE TITLE
Embedded structs don't work

### ISSUE THREAD

**Issue by GeorgeErickson** [mgutz/dat#5]
Minimal test case [here](https://gist.github.com/GeorgeErickson/cc482d6e23dce93226bf) here.

It gives ```panic: missing destination name user_id``` when it should populate the embedded struct.

**Comment by mgutz** [comment]
You might want to look at SelectDoc. It will hydrate deeply nested structures using JSON.Marshal in one trip to database. SelectDoc is much more flexible. Requires Postgres 9.3+

https://github.com/mgutz/dat/blob/master/v1/sqlx-runner/select_doc_test.go

**Comment by GeorgeErickson** [comment]
Yea, I'm loving that feature for `has_many` style relationships.

It would be good to have something for `has_one` style relationships.

e.g
```sql
SELECT
  o.*,
  a.street as address_street,
  a.street2 as address_street2,
  a.city as address_city,
  a.state as address_state,
  a.zip as address_zip,
  a.phone as address_phone,
  a.lat as address_lat,
  a.lon as address_lon,

FROM orders AS o
  LEFT OUTER JOIN addresses AS a
    ON o.address_id = a.id
```

**Comment by mgutz** [comment]
It seems sqlx only supports simple embeds https://github.com/jmoiron/sqlx/issues/112

I added `HasOne` and `HasMany` (`As` alias)
