### ISSUE TITLE
Something change recently with dat.v1?

### ISSUE THREAD

**Issue by jmickjr** [mgutz/dat#53]
I'm getting the following error when pulling v1. Any suggestions welcome and solicited.

$ go get -u gopkg.in/mgutz/dat.v1
package gopkg.in/mgutz/dat.v1: no buildable Go source files in /Users/jmick200/Dropbox/JMickJrRoot/MyDev/dropbox_cc/repo_yggdrasil/src/gopkg.in/mgutz/dat.v1

**Comment by mgutz** [comment]
SORRY, looks like I tagged a v2 fix as 1.x. Will fix.

**Comment by mgutz** [comment]
i deleted the tag, probably best to wipe out dat.v1 folder then `go get`
