### ISSUE TITLE
Outdated test instructions

### ISSUE THREAD

**Issue by GeorgeErickson** [mgutz/dat#6]
I would have submitted #5 with a test case, except the ```"github.com/mgutz/godo/v2"``` repo is private so I cannot run the tests.

**Comment by mgutz** [comment]
Sorry, I'm refactoring Godo. It just needs some document. I will be have it up by end of week.

**Comment by GeorgeErickson** [comment]
Also missing `github.com/mgutz/jo/v1`, which looks pretty awesome for testing.

**Comment by mgutz** [comment]
oops, forgot about that ... done
