### ISSUE TITLE
What's the state of v2?

### ISSUE THREAD

**Issue by poffe** [mgutz/dat#61]
First of all, thanks for the logxi library! Been using it for quite some time now.

Dat looks very promising since I'm already using both logxi and sqlx, but what's the state of v2? Should I start using it right away or should I wait?

Best regards, Christoffer

**Comment by mgutz** [comment]
We use v2 internally within our company and gets most of my attention. I will be doing a minor update in the next couple of weeks. The next v2 minor release is the unintuitively named branch `mgutz/jsql`.

**Comment by poffe** [comment]
Ok, great to know. Thanks for the quick reply!

**Comment by poffe** [comment]
Just a quick status check again, when do you expect `mgutz/jsql` to be merged into `v2` roughly?

**Comment by mgutz** [comment]
By next week

**Comment by poffe** [comment]
Great, thnx!
