### ISSUE TITLE
logxi

### ISSUE THREAD

**Issue by Xioshock** [mgutz/dat#64]
Hello,

after yesterdays commit with logxi, we can no longer build our application.

It says:
`gopkg.in\mgutz\dat.v1\init.go:7:2: no buildable Go source files in .....\github.com\mgutz\logxi`

We tried deleting all packages and installing them again, updating, etc. Same error everytime.

Could you check it out please?

Thank you

**Comment by mgutz** [comment]
My guess is you're not using glide?

Please read  [INSTALL.md](https://github.com/mgutz/dat/blob/v1/INSTALL.md)

**Comment by Xioshock** [comment]
Yes, we don't use glide. I didn't notice the readme has been changed. Thank you.

**Comment by mgutz** [comment]
You may have already figured it out but you need to be in `$GOPATH/src` not `$GOPATH` if installing to GOPATH. I updated INSTALL.md
