### ISSUE TITLE
Current status of dat project

### ISSUE THREAD

**Issue by kenkouot** [mgutz/dat#72]
Hello @mgutz! I've noticed this project has gone stale recently. Any updates on project status?

**Comment by mgutz** [comment]
The project is very much alive and in use in our live apps. I'm waiting for golang/dep to settle. Many developers disagreed with my decision to abandon gopkg.in (for good reasons) in favor of glide. We've since switched to golang/dep internally not because it is better rather it has the most potential to be a standard.

**Comment by JelteF** [comment]
I'm using dep in my own projects as well (and it's definitely better than glide). Is it already possible to use dat v3 in that case? Or should I still follow the big warning in the README on that branch.

**Comment by richp10** [comment]
With respect @mgutz - the project looks great but it does not seem to be alive.  The build instructions have not worked for 9 months even though there are pull requests that would fix the problem.  You have clearly done a huge amount of work on this project - why not invite some of the people who have put forwards PRs to become collaborators so they can at least fix it so it can be installed?

**Comment by bkono** [comment]
Just curious, any updates on this? Dat is still my favorite api of the pg focused go libraries, but the lack of commits, issue triage, etc is a bit of a barrier to entry.

**Comment by richp10** [comment]
@bkono - I concluded it was dead and successfully used the fork https://github.com/Janulka/dat for a while - though I wanted to clean up dependency management a bit and replaced the logging package.. my coding might be a bit furry but feel free to use this if you want: https://github.com/richp10/dat

I would love to see a community supported hard fork of this wonderful project if @mgutz does not have time to maintain it.  The simplest approach would be simply to invite collaborators in with commit rights and continue working from the main repo.

**Comment by bkono** [comment]
@richp10 appreciate that. I've tried using go-pg on my most recent project, and while I made it work, it was a struggle to use my preferred approach. In contrast, I have found it considerably easier when using dat's supportive api, and would like to go back to this as my go-to lib.

It looks like @helloeave and @pascallouisperez have also kicked off a recently updated fork. While getting contributions back to this repo would be ideal, I'd be willing to pitch in on a hard fork if theres interest from the community. For my personal usage, aside from building and dependency management fixes, I'd like to see a logger interface used to avoid the current hard dependency. Theres a few other niceities I'd like to add as well.... Let me know if theres interest in turning one of these forks into a canonical repo.

**Comment by pascallouisperez** [comment]
We'd love to see contributions at https://github.com/helloeave/dat which we are now using for all of our systems, and plan to support. cc @cbelsole, @pastormt

What are your thoughts @bkono @richp10? We'd be happy to turn our fork into a canonical repo, and start aggregating feature requests there.

**Comment by richp10** [comment]
I would strongly support that @pascallouisperez - I'm a bit newbie to golang and am not sure how likely it is that I would have PR's to contribute.. but would help as best I was able.  Feel free to look at my fork.. the main thing I would really need to start using your fork would be to get rid of the logxi dependency which I found to be causing all sorts of problems.. A close read of Janulka/dat would be even more useful. 

My other strong suggestions would be moving to dep and maybe clarifying the confusing branch structure.  When trying to understand the project it looks like it was being branched to all sorts of new features without having a stable 'core' that was properly usable. I don't mean to sound ungrateful to @mgutz who did an amazing job creating this library, but it really does deserve a loving home!

I would even wonder out loud whether a hard fork and rebranding might be considered I tried all the competitors and found this by far the easiest to work with and it could become *far* better known.

**Comment by bkono** [comment]
@pascallouisperez @richp10 I think making the swap is a great idea. Count me in for helping with feature requests / PRs wherever I can be helpful. 

Agreed on the logger issue ... @pascallouisperez we should start a discussion going on your repo for ideas to address that. I've got a few rolling around, but need to take another run through of the codebase and firm up my thoughts.

**Comment by richp10** [comment]
@pascallouisperez - can you enable 'issues' tracking on your repo and I will punt some thoughts there..

**Comment by pascallouisperez** [comment]
Here we go, issues enabled https://github.com/helloeave/dat/issues

Super down to remove `logxi` dependency ;)

**Comment by Narven** [comment]
Another dead project?
