### ISSUE TITLE
Is SQL injection possible?

### ISSUE THREAD

**Issue by ekanna** [mgutz/dat#8]
If i am running a query like below, is sql injection possible?

``` go
var json []byte
json, _ = con.SQL(`SELECT id, user_name, created_at FROM users WHERE user_name = $1 `,
    "mario",
).QueryJSON()
```
If yes, how to modify this query to prevent SQL injection?

Thanks for this package. It has saved me lot of boilerplate code.

**Comment by mgutz** [comment]
No. If Interpolation is disabled prepared statements are used by the underlying database/sql driver. If interpolation is on, `dat` relies on PostgreSQL's `E` operator which is described in Interpolation Safety in the README. Basically, newer versions of PostgreSQL disable all C-style escapes by default and `dat` verifies the setting at initialization and will panic if the setting is unsafe.

**Comment by ekanna** [comment]
Thanks a lot!
